services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      - n8n_mongo_network

  n8n:
    image: n8nio/n8n
    container_name: n8n_2
    ports:
      - "5678:5678"
    restart: always
    networks:
      - n8n_mongo_network

networks:
  n8n_mongo_network:
    driver: bridge
